### ISSUE TITLE
Add option to choose colors by icon name

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/directory-colorfy#13]
When somebody has a large list of icons, they COULD go through a renaming process at the command line, but being able to have something like:

```
"apply": {
    "icons": ["bear", "cat", "moose"],
    "colors": ["white", "blue", "orange"]
} 
```

Would be really nice. Especially if we can glob the icons.

**Comment by jefflembeck** [comment]
We have a PR here - https://github.com/filamentgroup/directory-colorfy/pull/3 that we can start with, build off of, etc.

**Comment by jefflembeck** [comment]
Side note: I don't want to have to turn off colors in filenames for this to work. I want to be able to handle both at the same time. I'm not sure what I want is the smart choice right now, so I'm writing out some API to make some decisions

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/directory-colorfy/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
